backend:
  name: test-repo
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "roadmaps"
    label: "Roadmaps"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Duration", name: "duration", widget: "string" }
      - { label: "Difficulty", name: "difficulty", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
